# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DummyAPI-FinalProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DummyAPI-FinalProject
	
	pod 'SwiftyJSON', '~> 4.0'
	pod 'Alamofire', '~> 5.4'
	pod 'NVActivityIndicatorView'
	pod 'IQKeyboardManagerSwift'

end
